# Generated by Django 5.0.2 on 2024-02-26 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
    ]
